version: "3.7"

services:
  db:
    image: ganjoor/ganjoor-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NANE

  api:
    build:
      context: .
    ports:
      - "8080:80"
    links:
      - db:mysql
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    environment:
      XDEBUG_CONFIG: remote_host=$XDEBUG_REMOTE_HOST remote_port=$XDEBUG_REMOTE_PORT idekey=$XDEBUG_IDEKEY

networks:
  default:
    external: true
    name: localnet