version: "3.7"

services:
  db:
    image: ganjoor/ganjoor-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ganjoor

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    links:
      - db:mysql
    depends_on:
      - db
    volumes:
      - .:/var/www/html/

networks:
  default:
    external: true
    name: localnet